// Code generated by protoc-gen-go-http. DO NOT EDIT.

package example

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/demo.example.Service/CreateBook",
				FunctionName:     "CreateBook",
				Path:             "/applications/",
				Method:           "POST",
				Resource:         "application",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "create"},
			},
		},
	}
	return set
}
